/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IReceiptNFT__factory } from "./IReceiptNFT__factory";
export { PayAndReceipt__factory } from "./PayAndReceipt__factory";
