/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReceiptNFT,
  IReceiptNFTInterface,
} from "../../../contracts/PayAndReceipt.sol/IReceiptNFT";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "string",
        name: "uri",
        type: "string",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReceiptNFT__factory {
  static readonly abi = _abi;
  static createInterface(): IReceiptNFTInterface {
    return new Interface(_abi) as IReceiptNFTInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IReceiptNFT {
    return new Contract(address, _abi, runner) as unknown as IReceiptNFT;
  }
}
